name: jordan_tourism
description: "Jordan Tourism App - Explore the wonders of Jordan"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  audioplayers: ^6.6.0
  google_generative_ai: ^0.4.7
  http: ^1.6.0
  flutter_markdown_plus: ^1.0.7
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
